if: tag IS present OR type = pull_request OR (branch = master AND type = push)   # we only CI the master, tags and PRs

language: python
cache: pip
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - pip install coveralls
  - python -m mypy alertaclient/
  - pytest --cov=alertaclient
  - coveralls
